name: Checker

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      CVEs: ${{ steps.validator.outputs.CVEs }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install
        run: |
          npm install

      - name: Run validator
        id: validator
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          node index.js

  echo:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: echo output
        env:
          OUTPUT: ${{ toJson(needs.job1) }}
        run: |
          echo "$OUTPUT"

  create-issues:
    needs: job1
    if: ${{ success() }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.job1.outputs.CVEs }}
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dblock/create-a-github-issue@v3
        with:
          update_existing: false
          search_existing: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CVE_ID: ${{ matrix }}
          ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
