name: Checker

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install
        run: |
          npm install

      - name: Run validator
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DEBUG: '*'
        run: |
          node index.js

  create-issues:
    needs: check
    if: ${{ always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.check.outputs.CVEs) }}
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dblock/create-a-github-issue@v3
        with:
          update_existing: false
          search_existing: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CVE_ID: ${{ matrix }}
          ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
